-- CREACIÓN DE SECUENCIAS --

CREATE SEQUENCE seq_artistas START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_generos START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_albumes START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_canciones START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_usuarios START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_playlists START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_playlist_canciones START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_historial_reproducciones START WITH 1 INCREMENT BY 1 NOCACHE;

-- INSERTS DE LA TABLA ARTISTAS --

INSERT INTO artistas (id_artista, nombre, pais)
VALUES (seq_artistas.NEXTVAL, 'Coldplay', 'Reino Unido');

INSERT INTO artistas (id_artista, nombre, pais)
VALUES (seq_artistas.NEXTVAL, 'The Weeknd', 'Canadá');

INSERT INTO artistas (id_artista, nombre, pais, fecha_debut, biografia, verificado)
VALUES (seq_artistas.NEXTVAL, 'The Weeknd', 'Canadá', '28/11/2025', 'Artista nº a nivel mundial', 'S');

INSERT INTO artistas (id_artista, nombre, pais, fecha_debut, biografia, verificado) VALUES (seq_artistas.NEXTVAL, 'Bad Bunny', 'Puerto Rico', '15/08/2016', 'Cantante y compositor urbano reconocido internacionalmente', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Dua Lipa', 'Reino Unido', '12/06/2015', 'Artista pop con múltiples premios musicales', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Rosalía', 'España', '10/02/2017', 'Reconocida por fusionar flamenco con estilos modernos', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'BTS', 'Corea del Sur', '13/06/2013', 'Grupo de K-Pop con impacto global', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Ed Sheeran', 'Reino Unido', '26/09/2011', 'Cantautor influyente en la música pop y acústica', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Karol G', 'Colombia', '04/07/2017', 'Cantante urbana destacada en la escena latina', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Billie Eilish', 'Estados Unidos', '29/03/2016', 'Artista pop conocida por su estilo único', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Adele', 'Reino Unido', '28/01/2008', 'Cantante de soul con múltiples premios Grammy', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'J Balvin', 'Colombia', '27/05/2009', 'Uno de los máximos exponentes del reggaetón', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Shakira', 'Colombia', '24/10/1991', 'Artista latina con presencia mundial', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Linkin Park', 'Estados Unidos', '24/10/2000', 'Banda de rock alternativo y nu metal con impacto global', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Rauw Alejandro', 'Puerto Rico', '12/02/2017', 'Cantante de reggaetón y R&B contemporáneo', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Justin Bieber', 'Canadá', '01/07/2009', 'Artista pop con gran impacto internacional', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Taylor Swift', 'Estados Unidos', '19/10/2006', 'Cantautora multipremiada y una de las más influyentes', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Sia', 'Australia', '15/08/1997', 'Cantautora con distintiva voz y estilo artístico', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Maluma', 'Colombia', '01/06/2011', 'Artista urbano latino de alcance global', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Harry Styles', 'Reino Unido', '12/05/2017', 'Cantante pop global y exmiembro de One Direction', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Anitta', 'Brasil', '06/04/2013', 'Cantante brasileña influyente en la música latina', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Maroon 5', 'Estados Unidos', '25/06/2002', 'Banda pop rock con múltiples éxitos mundiales', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Imagine Dragons', 'Estados Unidos', '15/09/2012', 'Banda de rock alternativo con renombre global', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Rihanna', 'Barbados', '30/08/2005', 'Cantante y empresaria con influencia mundial', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Ozuna', 'Puerto Rico', '15/01/2016', 'Artista urbano con récords de ventas', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Becky G', 'Estados Unidos', '04/04/2014', 'Cantante pop y urbana de origen latino', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Sam Smith', 'Reino Unido', '23/10/2012', 'Artista pop y soul con voz distintiva', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Luis Fonsi', 'Puerto Rico', '12/09/1998', 'Cantante pop y baladista reconocido globalmente', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Sech', 'Panamá', '10/03/2017', 'Cantante urbano con estilo melódico', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'The Kid LAROI', 'Australia', '18/05/2019', 'Joven artista de rap y pop', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'TINI', 'Argentina', '18/03/2016', 'Cantante argentina con proyección internacional', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Myke Towers', 'Puerto Rico', '11/01/2016', 'Rapper y cantante urbano destacado', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Doja Cat', 'Estados Unidos', '05/04/2018', 'Artista pop/rap con éxitos globales', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Post Malone', 'Estados Unidos', '20/08/2015', 'Rapper y cantante con estilo híbrido', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Jhay Cortez', 'Puerto Rico', '15/07/2017', 'Artista urbano y compositor reconocido', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Nathy Peluso', 'Argentina', '01/10/2017', 'Cantante y performer con estilo único', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Lola Índigo', 'España', '14/01/2018', 'Artista pop y urbana española', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'QUEEN', 'Reino Unido', '13/07/1973', 'Mítica banda de rock', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'AC/DC', 'Australia', '31/12/1975', 'Legendaria banda de rock duro', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Metallica', 'Estados Unidos', '06/03/1983', 'Banda icónica de heavy metal', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Arctic Monkeys', 'Reino Unido', '23/01/2006', 'Banda de rock alternativo británica', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Gorillaz', 'Reino Unido', '26/03/2001', 'Banda virtual de rock alternativo', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Kendrick Lamar', 'Estados Unidos', '14/09/2012', 'Uno de los raperos más influyentes de su generación', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Travis Scott', 'Estados Unidos', '16/10/2013', 'Rapper y productor musical', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Queen Latifah', 'Estados Unidos', '15/11/1989', 'Pionera del rap femenino y actriz', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Eminem', 'Estados Unidos', '23/02/1999', 'Uno de los raperos más exitosos del mundo', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Drake', 'Canadá', '14/06/2006', 'Rapero y cantante con impacto global', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'C. Tangana', 'España', '17/10/2011', 'Artista español de música urbana y fusión', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Maná', 'México', '02/02/1986', 'Banda mexicana de rock latino', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Luis Miguel', 'México', '12/01/1982', 'Cantante latino legendario', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'CNCO', 'Estados Unidos', '26/01/2016', 'Boyband latina con éxitos globales', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Morat', 'Colombia', '13/06/2015', 'Banda de pop/folk colombiana', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Pablo Alborán', 'España', '10/11/2010', 'Cantautor español de baladas', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Camila Cabello', 'Estados Unidos', '25/03/2015', 'Cantante pop de origen cubano', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Selena Gomez', 'Estados Unidos', '19/07/2010', 'Cantante y actriz con reconocimiento global', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Lali', 'Argentina', '04/09/2014', 'Artista pop argentina', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Rels B', 'España', '09/05/2015', 'Cantante urbano español', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Paulo Londra', 'Argentina', '02/01/2018', 'Artista de trap argentino', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Feid', 'Colombia', '17/09/2016', 'Cantante urbano con estilo distintivo', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Eladio Carrión', 'Estados Unidos', '02/02/2017', 'Rapero y cantante urbano', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'Halsey', 'Estados Unidos', '27/10/2014', 'Cantante y compositora conocida por su estilo alternativo y letras emocionales', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'The Chainsmokers', 'Estados Unidos', '15/09/2012', 'Dúo de música electrónica y pop con múltiples éxitos globales', 'S');
INSERT INTO artistas VALUES (seq_artistas.NEXTVAL, 'AURORA', 'Noruega', '17/03/2015', 'Cantante y compositora con un estilo etéreo y único en la escena alternativa', 'S');

INSERT INTO generos (id_genero, nombre, descripcion)
VALUES (seq_generos.NEXTVAL, 'Pop', 'Género basado en melodías pegadizas y producción comercial orientada al público general');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Rock', 'Género centrado en guitarras eléctricas, batería y sonido enérgico');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Reggaetón', 'Género urbano con ritmos latinos y base rítmica de reggaetón clásico');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Trap', 'Estilo urbano caracterizado por ritmos lentos, graves marcados y letras explícitas');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'K-Pop', 'Pop coreano con coreografías, estética visual y producción cuidada');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'R&B', 'Género con influencias soul, pop y ritmo electrónico suave');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Hip-Hop', 'Cultura y música basada en rap, bases rítmicas y producción electrónica');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Electrónica', 'Música creada mediante sonidos digitales y sintetizadores');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'House', 'Subgénero electrónico con ritmos repetitivos y enfoque en el baile');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Indie Pop', 'Pop alternativo centrado en estética independiente y melodías suaves');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Indie Rock', 'Rock alternativo producido al margen de la industria comercial');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Metal', 'Género derivado del rock con distorsión elevada y sonido agresivo');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Jazz', 'Género musical improvisado con raíces afroamericanas y armonías complejas');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Soul', 'Género vocal y emocional con influencia del gospel y R&B');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Folk', 'Género centrado en instrumentos acústicos y tradición cultural');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Flamenco Fusión', 'Estilo que mezcla flamenco con géneros modernos como pop o urbano');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Dance', 'Música electrónica enfocada en ritmos bailables y repetitivos');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Alternativo', 'Etiqueta amplia para sonidos experimentales fuera de la música comercial');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Latin Pop', 'Pop moderno con ritmos y elementos de música latina');
INSERT INTO generos VALUES (seq_generos.NEXTVAL, 'Ambient', 'Música electrónica atmosférica centrada en texturas y sensaciones');

INSERT INTO albumes (id_album, titulo, id_artista, fecha_lanzamiento, numero_canciones, duracion_total)
VALUES (seq_albumes.NEXTVAL, 'After Hours', 4, '20/03/2020', 14, 56);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'YHLQMDLG', 5, '29/02/2020', 20, 65);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Future Nostalgia', 6, '27/03/2020', 11, 37);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'El Mal Querer', 7, '02/11/2018', 11, 30);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Map of the Soul: 7', 8, '21/02/2020', 20, 75);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Divide', 9, '03/03/2017', 16, 59);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'KG0516', 10, '25/03/2021', 24, 78);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'When We All Fall Asleep, Where Do We Go?', 11, '29/03/2019', 14, 42);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, '21', 12, '24/01/2011', 11, 48);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Vibras', 13, '25/05/2018', 15, 55);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Sale el Sol', 14, '19/10/2010', 15, 56);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Meteora', 15, '25/03/2003', 13, 36);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Purpose', 16, '13/11/2015', 19, 63);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, '1989', 17, '27/10/2014', 13, 48);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'This Is Acting', 18, '29/01/2016', 12, 46);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'F.A.M.E.', 19, '18/05/2018', 13, 50);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Fine Line', 20, '13/12/2019', 12, 47);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Kisses', 21, '05/04/2019', 13, 44);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Songs About Jane', 22, '25/06/2002', 12, 46);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Night Visions', 23, '04/09/2012', 13, 43);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Anti', 24, '28/01/2016', 13, 43);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Odisea', 25, '25/08/2017', 16, 60);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Mala Santa', 26, '17/10/2019', 16, 52);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'In the Lonely Hour', 27, '26/05/2014', 10, 32);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Vida', 28, '01/02/2019', 12, 45);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Sueños', 29, '19/04/2019', 11, 38);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'F*ck Love', 30, '24/07/2020', 15, 40);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'TINI', 31, '12/10/2016', 14, 49);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Easy Money Baby', 32, '24/01/2020', 16, 51);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Planet Her', 33, '25/06/2021', 14, 44);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Hollywood''s Bleeding', 34, '06/09/2019', 17, 51);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Timelezz', 35, '03/09/2021', 16, 54);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Calambre', 36, '02/10/2020', 12, 38);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Akelarre', 37, '17/05/2019', 12, 40);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'A Night at the Opera', 38, '21/11/1975', 12, 43);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Back in Black', 39, '25/07/1980', 10, 42);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Master of Puppets', 40, '03/03/1986', 8, 55);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'AM', 41, '09/09/2013', 12, 41);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Demon Days', 42, '11/05/2005', 15, 51);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'To Pimp a Butterfly', 43, '15/03/2015', 16, 79);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Astroworld', 44, '03/08/2018', 17, 58);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Black Reign', 45, '16/11/1993', 14, 61);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'The Marshall Mathers LP', 46, '23/05/2000', 18, 72);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Scorpion', 47, '29/06/2018', 25, 90);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'El Madrileño', 48, '26/02/2021', 14, 49);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, '¿Dónde Jugarán los Niños?', 49, '27/10/1992', 12, 55);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Romance', 50, '19/11/1991', 12, 45);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Primera Cita', 51, '26/08/2016', 14, 48);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Terral', 53, '11/11/2014', 15, 67);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Camila', 54, '12/01/2018', 11, 37);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Revival', 55, '09/10/2015', 14, 45);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Brava', 56, '10/08/2018', 13, 46);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Happy Birthday Flakko', 57, '21/11/2016', 8, 27);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Homerun', 58, '23/05/2019', 18, 68);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Ferxxo (Vol 1: M.O.R)', 59, '23/04/2020', 16, 54);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Sauce Boyz 2', 60, '02/12/2021', 22, 79);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Badlands', 61, '28/08/2015', 16, 52);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Memories... Do Not Open', 62, '07/04/2017', 12, 43);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'All My Demons Greeting Me as a Friend', 63, '11/03/2016', 12, 47);
INSERT INTO albumes VALUES (seq_albumes.NEXTVAL, 'Un Verano Sin Ti', 5, '06/05/2022', 23, 81);

INSERT INTO canciones (id_cancion, titulo, id_album, id_artista, id_genero, duracion, numero_pista, reproducciones, fecha_lanzamiento, letra)
VALUES (seq_canciones.NEXTVAL, 'Midnight Reflections', 61, 4, 19, 4, 1, 150000000, '20/03/20', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Barrio Sin Sueño', 62, 5, 2, 3, 1, 220000000, '29/02/20', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Retro Lights', 63, 6, 18, 4, 1, 180000000, '27/03/20', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Cielo Roto', 64, 7, 13, 4, 1, 95000000, '02/11/18', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Inner Map', 65, 8, 4, 4, 1, 210000000, '21/02/20', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Perfect Lines', 66, 9, 18, 4, 1, 175000000, '03/03/17', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Caribe en Llamas', 67, 10, 2, 4, 1, 160000000, '25/03/21', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Sleepwalker', 68, 11, 15, 3, 1, 240000000, '29/03/19', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Rolling Tears', 69, 12, 20, 5, 1, 300000000, '24/01/11', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Olas de Color', 70, 13, 16, 4, 1, 130000000, '25/05/18', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Rayos de Madrugada', 71, 14, 16, 4, 1, 110000000, '19/10/10', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Broken Meteors', 72, 15, 1, 3, 1, 250000000, '25/03/03', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Heartbeat Road', 73, 16, 18, 4, 1, 270000000, '13/11/15', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'City Polaroids', 74, 17, 18, 4, 1, 320000000, '27/10/14', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Paper Mask', 75, 18, 18, 4, 1, 140000000, '29/01/16', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Pasos de Fuego', 76, 19, 2, 3, 1, 155000000, '18/05/18', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Borderline Heart', 77, 20, 8, 4, 1, 260000000, '13/12/19', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Beso de Medianoche', 78, 21, 16, 3, 1, 120000000, '05/04/19', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Ventana de Jane', 79, 22, 9, 4, 1, 190000000, '25/06/02', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Radioactive Dreams', 80, 23, 9, 4, 1, 210000000, '04/09/12', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Desert Rose', 81, 24, 15, 4, 1, 175000000, '28/01/16', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Viaje Eterno', 82, 25, 2, 4, 1, 145000000, '25/08/17', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Ángel Caído', 83, 26, 2, 3, 1, 135000000, '17/10/19', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Empty Room', 84, 27, 20, 4, 1, 185000000, '26/05/14', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Luz de Mi Vida', 85, 28, 16, 4, 1, 95000000, '01/02/19', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Noches en Vela', 86, 29, 2, 3, 1, 90000000, '19/04/19', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Love War', 87, 30, 3, 3, 1, 160000000, '24/07/20', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Stage Lights', 88, 31, 16, 4, 1, 80000000, '12/10/16', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Calle Sin Miedo', 89, 32, 3, 3, 1, 115000000, '24/01/20', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Cosmic Queen', 90, 33, 18, 4, 1, 175000000, '25/06/21', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Neon Scars', 91, 34, 5, 4, 1, 200000000, '06/09/19', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Reloj Parado', 92, 35, 2, 3, 1, 105000000, '03/09/21', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Corriente en la Piel', 93, 36, 15, 4, 1, 95000000, '02/10/20', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Noche de Brujas', 94, 37, 16, 4, 1, 88000000, '17/05/19', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Curtain Call', 95, 38, 1, 4, 1, 130000000, '21/11/75', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Thunder Road', 96, 39, 1, 4, 1, 195000000, '25/07/80', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Strings of Fate', 97, 40, 10, 5, 1, 210000000, '03/03/86', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Late Night Radio', 98, 41, 9, 4, 1, 170000000, '09/09/13', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Plastic City', 99, 42, 15, 4, 1, 165000000, '11/05/05', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Skyline Poem', 100, 43, 5, 4, 1, 185000000, '15/03/15', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Rollercoaster Sky', 101, 44, 5, 4, 1, 190000000, '03/08/18', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Storm Crown', 102, 45, 5, 4, 1, 72000000, '16/11/93', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Shattered Mirror', 103, 46, 5, 4, 1, 250000000, '23/05/00', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Veneno Suave', 104, 47, 5, 4, 1, 210000000, '29/06/18', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Plaza en Llamas', 105, 48, 15, 4, 1, 140000000, '26/02/21', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Patio de Recuerdos', 106, 49, 1, 4, 1, 90000000, '27/10/92', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Bésame Despacio', 107, 50, 16, 4, 1, 130000000, '19/11/91', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Nervios de Medianoche', 108, 51, 16, 4, 1, 95000000, '26/08/16', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Viento del Sur', 109, 53, 18, 4, 1, 85000000, '11/11/14', 'Letra no disponible');
INSERT INTO canciones VALUES (seq_canciones.NEXTVAL, 'Havana Echoes', 110, 54, 16, 4, 1, 125000000, '12/01/18', 'Letra no disponible');



